# Generated by Django 2.2.5 on 2019-09-17 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='Weather',
        ),
    ]
