# Generated by Django 2.2.5 on 2019-09-17 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0002_auto_20190916_2024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weather',
            new_name='CurrentWeather',
        ),
    ]
